watermark:
  input_folder: "resources/input"
  opacity: 50
  npy_path: "watermark_normal_200"
  quality: 30
  output_height: 1000
  normal:
    handler: "process_normal_watermark"
    npy_path: "watermark_normal_200"
  foggy:
    handler: "process_foggy_watermark"
    npy_path: "watermark_foggy_450"